name: Sync Renovatebot Branch
on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  sync_renovatebot:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch branches
        run: |
          git fetch origin renovatebot:renovatebot
          git log renovatebot -1 --format=%H

      # Step 3: Check if renovatebot can be fast-forwarded to master
      - name: Check fast-forwardability
        id: check_fast_forward
        run: |
          if git merge-base --is-ancestor renovatebot master; then
            echo "Branch is ancestor"
            echo "can_fast_forward=true" >> "$GITHUB_ENV"
          else
            echo "Branch is not ancestor"
            echo "can_fast_forward=false" >> "$GITHUB_ENV"
          fi

      # Step 4: Fast-forward renovatebot to master if possible
      - name: Fast-forward renovatebot
        if: env.can_fast_forward == 'true'
        run: |
          git checkout renovatebot
          git merge --ff-only master
          git push origin renovatebot

      # Step 5: Output status
      - name: Output result
        run: |
          if [ "${{ env.can_fast_forward }}" == "true" ]; then
            echo "Branch 'renovatebot' was successfully fast-forwarded to 'master'."
          else
            echo "Branch 'renovatebot' cannot be fast-forwarded to 'master'."
          fi
